name: ci

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x86_64
            os: windows-2025
          - name: MacOS am latest
            os: macos-latest
          - name: MacOS 15 intel
            os: macos-15-intel
          - name: Linux x86_64
            os: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: cargo test --verbose

      - name: Build
        run: cargo build --verbose --release

      - name: List release directory (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: Get-ChildItem target/release | Format-Table -AutoSize

      - name: Upload Windows binaries
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: tlmc-windows-x86_64
          path: |
            target/release/split-album.exe
            target/release/scan-albums.exe
            target/release/apply-tags.exe
            target/release/*.dll
